config/routes.rb
Rails.application.routes.draw do
  root to: 'messages#index'

  resources :users
  resources :messages

  get '/active_users', to: "users#active_users", as: :active_users
end

app/models/Message.rb
class Message < ApplicationRecord
  validates_presence_of :description
  validates_presence_of :author
  validates_presence_of :dialect_type
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def check_current_user
    redirect_to new_user_path unless session[:current_user].present?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :check_current_user
  before_action :get_messages, only: [:index, :create]

  def new; end

  def index
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    unless @message.save
      flash.now[:error] = @message.errors.full_messages
    end

    render :index
  end

  private
  def message_params
    user = session[:current_user]
    message = params[:message][:description]
    translated_message = Translation.new(user["dialect"]).translate(message)
    { description: translated_message, author: user["username"], dialect_type: user["dialect"] }
  end

  def get_messages
    @messages = Message.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_current_user

  def new; end

  def create
    if params[:username].present? && params[:dialect].present?
      sessions_register
      redirect_to root_path
    else
      flash[:error] = "Please inform your username and choose a dialect"
      redirect_to new_user_path
    end
  end

  def active_users
    @users = session[:active_users]
    respond_to do |format|
      format.js { render layout: false, locals: { users: @users } }
    end
  end

  private
  def sessions_register
    session[:current_user] = { username: params[:username], dialect: params[:dialect] }
    session[:active_users] = session[:active_users].present? ? session[:active_users] : []
    session[:active_users] << { username: params[:username], dialect: params[:dialect] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def dialect_select_options(selected)
    options_for_select([["Yoda", "yoda"], ["Valley Girl", "valspeak"], ["Pirate", "pirate"]])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Translated Instant Messaging</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Translated Instant Messaging</a>
        </div>
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
      <div class="row">
        <!-- :flash-message -->
        <%= render "layouts/elements/flash_message" %>
        <!-- flash-message: -->

        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag "application" %>

    <%= yield :javascript %>
  </body>
</html>

app/views/layouts/elements/_flash_message.html.erb
<div id="notifications">
  <% flash.each do |name, message| %>
    <div class="alert fade in alert-<%= name == "notice" ? "success" : "danger" %>">
      <button data-dismiss="alert" class="close close-sm" type="button">
        <i class="fa fa-times"></i>
      </button>

      <% if message.is_a?(Array) %>
        <ul>
          <% message.each do |single_message| %>
            <li><%= single_message %></li>
          <% end %>
        </ul>
      <% else %>
        <%= message %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/messages/index.html.erb
<div class="row">
  <div class="col-lg-8">
    <h4>Chat messages</h4>
    <% @messages.each do |message| %>
      <div class="card">
        <div class="card-block">
          <div class="row">
            <div class="col-md-1">
              <%= image_tag(message.dialect_type, width: "40", height: "40") %>
            </div>
            <div class="col-md-11">
              <p class="card-text">
                <span class="text-muted"><b><%= message.author %></b> at <b><%= l message.created_at, format: :long %></b> says</span><br>
                <%= message.description %>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-lg-4" id="js-active-users" data-url="<%= active_users_path %>"></div>
</div>
<div class="row">
  <%= form_for @message, url: messages_path, method: "post" do |f| %>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
      <small class="text-muted">From 2 to 1000 characters</small>
    </div>

    <%= f.submit "Send message", class: 'btn btn-primary btn-lg' %>
  <% end %>
</div>

<% content_for :javascript do %>
  <script>
  $(function(){
    $.ajax({
      url: $('#js-active-users').data('url'),
      type: 'get',
      error: function(data){
        $('#js-active-users').html('It was not possible to bring the active users.');
      }
    });
   });
  </script>
<% end %>

app/views/users/_build_active_users.html.erb
<h4>Active users</h4>
<ul class="active-users">
  <% @users.each do |user| %>
    <li><%= image_tag("avatar-blank", width: "29", height: "29") %> <%= user["username"] %></li>
  <% end %>
</ul>

app/views/users/active_users.js.erb
$('#js-active-users').html("<%= j render(partial: 'build_active_users', locals: { users: @users }) %>")

app/views/users/new.html.erb
<h1>Login</h1>
<div class="row">
  <div class="col-lg-12">
    <%= form_tag(users_path, method: "post", class: "form") do %>

    <div class="form-group">
      <%= label_tag :username %>
      <%= text_field_tag("username", params[:username], { class: "form-control" }) %>
    </div>

    <div class="form-group">
      <%= label_tag :dialect %>
      <%= select_tag('dialect', dialect_select_options(params[:dialect]), class: "form-control", include_blank: "Please select a dialect") %>
    </div>

    <%= submit_tag "Login", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>